cloud:
  aws:
    credentials:
      access-key: AKIAS3FBM75Y6JTHO5HL
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: myawsbuckettestothman


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090
